import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'sonner';
import { ConnectivityProvider } from '@/components/ConnectivityProvider';
import OfflineOverlay from '@/components/OfflineOverlay';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full bg-black text-white overflow-x-hidden flex flex-col font-sans`}
      >
        <main className="w-full h-full flex-1 flex flex-col">
          <ConnectivityProvider>
            {children}
            <OfflineOverlay />
          </ConnectivityProvider>
        </main>
        <Toaster position="top-center" richColors />
        <footer>
          <p className="text-center py-4 text-xs opacity-50">&copy; 2025 SAB Game. Todos los derechos reservados.</p>
        </footer>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                        if ('serviceWorker' in navigator) {
                            window.addEventListener('load', function() {
                                navigator.serviceWorker.register('/sw.js').then(function(registration) {
                                    console.log('ServiceWorker registration successful with scope: ', registration.scope);
                                }, function(err) {
                                    console.log('ServiceWorker registration failed: ', err);
                                });
                            });
                        }
                        `,
          }}
        />
      </body>
    </html>
  );
}
